# Generated by Django 5.1.1 on 2024-09-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videogames_manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record_calendar",
            name="updated_at",
            field=models.DateField(blank=True, null=True),
        ),
    ]
