# Generated by Django 5.1.1 on 2024-09-28 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("videogames_manager", "0002_alter_record_calendar_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="record_calendar",
            name="month",
        ),
    ]
