# Generated by Django 5.1.1 on 2024-10-04 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videogames_manager", "0003_remove_record_calendar_month"),
    ]

    operations = [
        migrations.AlterField(
            model_name="games_releases",
            name="updated_at",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="games_updated",
                to="videogames_manager.record_calendar",
            ),
        ),
        migrations.CreateModel(
            name="Games_Genres",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="videogames_manager.games_releases",
                    ),
                ),
            ],
        ),
    ]
