# Generated by Django 5.1.1 on 2024-10-04 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videogames_manager", "0004_alter_games_releases_updated_at_games_genres"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="games_genres",
            name="game",
        ),
        migrations.AddField(
            model_name="games_releases",
            name="genres",
            field=models.ManyToManyField(
                related_name="games", to="videogames_manager.games_genres"
            ),
        ),
        migrations.AddField(
            model_name="games_releases",
            name="summary",
            field=models.CharField(default=123, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="games_genres",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
