# Generated by Django 5.1.1 on 2024-10-05 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "videogames_manager",
            "0005_remove_games_genres_game_games_releases_genres_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="followed_games",
            field=models.ManyToManyField(
                related_name="followers", to="videogames_manager.games_releases"
            ),
        ),
    ]
