# Generated by Django 5.1.1 on 2024-10-06 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videogames_manager", "0006_user_followed_games"),
    ]

    operations = [
        migrations.CreateModel(
            name="Games_Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Games_Platforms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Games_Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Games_Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("release_date", models.DateField()),
                ("franchise", models.CharField(max_length=255)),
                ("storyline", models.TextField()),
                ("summary", models.TextField()),
                ("websites", models.URLField(max_length=300)),
                ("cover_url", models.URLField(max_length=300)),
                (
                    "genres",
                    models.ManyToManyField(
                        related_name="games_genres",
                        to="videogames_manager.games_genres",
                    ),
                ),
                (
                    "record_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="games_record_year",
                        to="videogames_manager.record_calendar",
                    ),
                ),
                (
                    "updated_at",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="games_updated",
                        to="videogames_manager.record_calendar",
                    ),
                ),
                (
                    "language",
                    models.ManyToManyField(
                        related_name="games_languages",
                        to="videogames_manager.games_language",
                    ),
                ),
                (
                    "platform",
                    models.ManyToManyField(
                        related_name="games_platforms",
                        to="videogames_manager.games_platforms",
                    ),
                ),
                (
                    "status",
                    models.ManyToManyField(
                        related_name="games_status",
                        to="videogames_manager.games_status",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="followed_games",
            field=models.ManyToManyField(
                related_name="followers", to="videogames_manager.games_data"
            ),
        ),
        migrations.DeleteModel(
            name="Games_Releases",
        ),
    ]
