# Generated by Django 5.1.1 on 2024-10-06 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "videogames_manager",
            "0007_games_language_games_platforms_games_status_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="games_data",
            name="language",
        ),
        migrations.DeleteModel(
            name="Games_Language",
        ),
    ]
