# Generated by Django 5.1.1 on 2024-10-06 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videogames_manager", "0008_remove_games_data_language_delete_games_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="games_data",
            name="franchise",
            field=models.CharField(max_length=50),
        ),
    ]
