# Generated by Django 5.1.1 on 2024-10-07 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("videogames_manager", "0009_alter_games_data_franchise"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="games_data",
            name="status",
        ),
        migrations.DeleteModel(
            name="Games_Status",
        ),
    ]
