# Generated by Django 5.1.1 on 2024-10-08 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videogames_manager", "0010_remove_games_data_status_delete_games_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="games_data",
            name="cover_url",
        ),
        migrations.AddField(
            model_name="games_data",
            name="cover_id",
            field=models.IntegerField(default=0),
        ),
    ]
