# Generated by Django 5.1.1 on 2024-10-08 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videogames_manager", "0011_remove_games_data_cover_url_games_data_cover_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="games_data",
            name="cover_id",
            field=models.CharField(max_length=255),
        ),
    ]
