# Generated by Django 5.1.1 on 2024-10-14 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("videogames_manager", "0012_alter_games_data_cover_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="games_data",
            name="franchise",
        ),
        migrations.RemoveField(
            model_name="games_data",
            name="websites",
        ),
    ]
